#!/usr/bin/env python3
"""2D fab drawing for the Ti back-shell v3.0 0.6mm-board DUMB BOX (1.00 floor, 0.60 board, U7 pocket, NO ribs, NO locator
pillars -- the resin H-brace carries center support + registers by fitment) -> PDF + PNG."""
import numpy as np, matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt
from matplotlib.patches import Rectangle, Polygon as MplPoly

# Heights come from enclosure/part_heights.py -- the single home, verified against each
# part's 3D model by check_consistency [7]. This sheet DERIVES the U7 relief pocket from
# them exactly as the CAD generator does, instead of restating it: the pocket existed for
# a 1.75 mm SOIC-8 U7 that the v4 board does not carry, and on 2026-07-28 it was removed
# from the STEP by arithmetic while this drawing kept showing it in Detail B -- a feature
# a shop would have machined from a sheet the model disagreed with.
import os as _o, sys as _s
_s.path.insert(0, _o.path.join(_o.path.dirname(_o.path.abspath(__file__))))
from part_heights import HEIGHTS as _PH, SUPERCAP_H as _CAPH   # noqa: E402
U7_H       = _PH["U7"]
U7_POCKET  = max(0.0, round(U7_H - _CAPH, 3))     # 0.0 on the v4 board -> no pocket drawn

# The rear art -- two reeded fin fields + the medallion -- is MACHINED-IN geometry, so this
# sheet draws it as reference and quotes its numbers FROM ITS OWN SOURCES (fit_rules /
# medallion), never re-declared, for the same reason the U7 pocket is derived above. This
# sheet said "REAR ART LASER-MARKED" until 2026-07-31, two eras after that plan died: the
# drawing regenerated byte-identical through the fin deepening AND the medallion because
# nothing here was a function of either. Now it is.
import fit_rules as _fr        # noqa: E402
import medallion as _mdl       # noqa: E402
_MCY = sum(_fr.fin_band()) / 2.0                  # medallion centre = the clear-band centre

W,H,R = 50.80,88.90,3.0
wall,lip_w,floor,cavity,board,border = 1.0,2.5,1.00,1.80,0.60,0.15   # lip_w here = WEST lip shown in Section A-A
lip_W,lip_N,lip_S,lip_E,lip_Ew = 2.5,2.0,2.0,1.0,2.5
bbw = 2.0                                   # SYMMETRIC exterior back-border width (uniform 4 sides); front lip stays asymmetric
Wb,Hb = 50.80,88.90
boss_r,pilot_r,cbore,ease = 2.60,0.80,3.0,0.10
ef=-0.05
cavW,cavH,cavR = W+2*ef,H+2*ef,R+ef
outW,outH,outR = cavW+2*wall,cavH+2*wall,cavR+wall
bb,wt = floor+cavity, floor+cavity+board
lb = 0.10                                  # light interior edge-breaks (felt, not seen), 45deg
# Mounts and EVERY dimension derived from them come from fit_rules -- the same one home the
# shell CAD reads. This sheet held its own literal copy until 2026-08-03, alongside six
# hardcoded dimension strings, and when the board's mounts were nudged 0.13 mm diagonally the
# copy went stale: the sheet a machinist would have cut to still called the hole pitch
# "44.80 ±0.05" when the board had become 45.06 -- **0.26 mm out, 5.2x the tolerance printed
# beside it.** A drawing that is wrong is worse than a drawing that is missing, so nothing
# about the hole pattern is typed here any more; it is computed, below, from MOUNTS.
mounts = _fr.MOUNTS
_mx = sorted({m[0] for m in mounts})        # 2 columns
_my = sorted({m[1] for m in mounts})        # 4 rows
oxmin,oymin = -0.95,-0.95
_oxmax = 51.75                              # outline east edge, the datum the edge dims run to

INK="#111111"; GRY="#9a9a9a"; HATCH="#e8e8e8"
fig=plt.figure(figsize=(420/25.4,297/25.4))
ax=fig.add_axes([0,0,1,1]); ax.set_xlim(0,420); ax.set_ylim(0,297)
ax.set_aspect("equal"); ax.axis("off"); fig.patch.set_facecolor("white")
ax.add_patch(Rectangle((8,8),404,281,fill=False,ec=INK,lw=1.2))
ax.add_patch(Rectangle((10,10),400,277,fill=False,ec=INK,lw=0.4))

def rrect(x,y,w,h,r,n=12):
    p=[]; cs=[(x+w-r,y+r),(x+w-r,y+h-r),(x+r,y+h-r),(x+r,y+r)]; a0=[-90,0,90,180]
    for (cx,cy),a in zip(cs,a0):
        for t in np.linspace(np.radians(a),np.radians(a+90),n): p.append((cx+r*np.cos(t),cy+r*np.sin(t)))
    return p
def dim(p0,p1,off,text,vert=False,fs=7,side=1,txtoff=1.6):
    (x0,y0),(x1,y1)=p0,p1
    if vert:
        xd=off
        ax.plot([x0,xd+1.6*side],[y0,y0],lw=0.4,color=INK); ax.plot([x1,xd+1.6*side],[y1,y1],lw=0.4,color=INK)
        ax.annotate("",xy=(xd,y0),xytext=(xd,y1),arrowprops=dict(arrowstyle="<|-|>",lw=0.5,color=INK,mutation_scale=8,shrinkA=0,shrinkB=0))
        ax.text(xd-txtoff*side,(y0+y1)/2,text,ha="right" if side>0 else "left",va="center",fontsize=fs,rotation=90,color=INK)
    else:
        yd=off
        ax.plot([x0,x0],[y0,yd+1.6*side],lw=0.4,color=INK); ax.plot([x1,x1],[y1,yd+1.6*side],lw=0.4,color=INK)
        ax.annotate("",xy=(x0,yd),xytext=(x1,yd),arrowprops=dict(arrowstyle="<|-|>",lw=0.5,color=INK,mutation_scale=8,shrinkA=0,shrinkB=0))
        ax.text((x0+x1)/2,yd+txtoff*side,text,ha="center",va="bottom" if side>0 else "top",fontsize=fs,color=INK)
def leader(xp,yp,xt,yt,text,ha="left",fs=6.6,va="center"):
    ax.annotate("",xy=(xp,yp),xytext=(xt,yt),arrowprops=dict(arrowstyle="-|>",lw=0.45,color=INK,mutation_scale=7,shrinkA=0,shrinkB=2))
    ax.text(xt+(0.8 if ha=='left' else -0.8),yt,text,ha=ha,va=va,fontsize=fs,color=INK)
def fcf(x,y,cells,h=4.6,fs=6.6):
    cx=x
    for c in cells:
        w=max(7.0,2.6+len(c)*1.95); ax.add_patch(Rectangle((cx,y),w,h,fill=False,ec=INK,lw=0.5))
        ax.text(cx+w/2,y+h/2,c,ha="center",va="center",fontsize=fs,color=INK); cx+=w
    return cx,y+h/2

# ===================== PLAN (back face) =====================
S1=1.5; Px,Py=42,112
X=lambda bx:Px+(bx-oxmin)*S1; Y=lambda by:Py+(by-oymin)*S1
ax.add_patch(MplPoly(rrect(X(oxmin),Y(oymin),outW*S1,outH*S1,outR*S1),closed=True,fill=False,ec=INK,lw=1.0))
ax.add_patch(MplPoly(rrect(X(oxmin)+wall*S1,Y(oymin)+wall*S1,cavW*S1,cavH*S1,cavR*S1),closed=True,fill=False,ec=GRY,lw=0.5))
_afw,_afh = cavW-2*bbw, cavH-2*bbw          # symmetric recessed art field (equal 2.0 border all sides)
ax.add_patch(MplPoly(rrect(X(0.05+bbw),Y(0.05+bbw),_afw*S1,_afh*S1,max(cavR-bbw,0.3)*S1),closed=True,fill=False,ec=INK,lw=0.8))
for lx,ly,rot in [(0.05+bbw/2,44,90),(Wb-0.05-bbw/2,44,90),(25.4,0.05+bbw/2,0),(25.4,Hb-0.05-bbw/2,0)]:
    ax.text(X(lx),Y(ly),"2.0",ha="center",va="center",fontsize=4.8,color="#2f5bd0",rotation=rot)
for mx,my in mounts:
    ax.add_patch(plt.Circle((X(mx),Y(my)),boss_r*S1,fill=False,ec=GRY,lw=0.5))
    ax.add_patch(plt.Circle((X(mx),Y(my)),cbore/2*S1,fill=False,ec=GRY,lw=0.5))
    ax.add_patch(plt.Circle((X(mx),Y(my)),pilot_r*S1,fill=False,ec=INK,lw=0.9))
    ax.plot([X(mx)-1.6*S1,X(mx)+1.6*S1],[Y(my),Y(my)],lw=0.4,color=INK)
    ax.plot([X(mx),X(mx)],[Y(my)-1.6*S1,Y(my)+1.6*S1],lw=0.4,color=INK)
# REAR ART (reference): the two reeded fin fields and the medallion, drawn from their own
# sources. Zones dashed, every rib outlined from fit_rules.fin_ribs() (the real stadium
# polygons, boss wraps and all), medallion circles from medallion.py's constants. STEP governs.
for _zone, _cys in _fr.fin_runs():
    for _zp in (_zone.geoms if _zone.geom_type == "MultiPolygon" else [_zone]):
        ax.add_patch(MplPoly([(X(px), Y(py)) for px, py in _zp.exterior.coords],
                             closed=True, fill=False, ec=GRY, lw=0.4, ls=(0, (3, 1.6))))
for _rp in _fr.fin_ribs():
    ax.add_patch(MplPoly([(X(px), Y(py)) for px, py in _rp.exterior.coords],
                         closed=True, fill=False, ec=GRY, lw=0.22))
ax.add_patch(plt.Circle((X(25.4), Y(_MCY)), (_mdl.COIN_R + _mdl.RIM_W) * S1,
                        fill=False, ec=GRY, lw=0.55))
for _rr in (_mdl.COIN_R, sum(_mdl.HOOP) / 2.0, _mdl.R_TEXT):
    ax.add_patch(plt.Circle((X(25.4), Y(_MCY)), _rr * S1,
                            fill=False, ec=GRY, lw=0.28, ls=(0, (3, 1.6))))
leader(X(25.4 + 9.4), Y(_MCY - 9.4), 124, 196, "MEDALLION (REF — REAR ART BLOCK)", fs=5.2)
leader(X(46.0), Y(75.0), 124, 228, "REEDED FIELDS ×2 (REF — REAR ART BLOCK)", fs=5.2)

# U7 relief pocket (cavity-floor recess; hidden in back-face view -> dashed).
# Drawn ONLY if the arithmetic still calls for one -- see the import block above.
u7x,u7y,pw,ph = 28.1,37.3,7.8,5.4
if U7_POCKET > 0:
    ax.add_patch(MplPoly(rrect(X(u7x-pw/2),Y(u7y-ph/2),pw*S1,ph*S1,1.0*S1),closed=True,fill=False,ec=GRY,lw=0.6,ls=(0,(4,2))))
    leader(X(u7x-pw/2),Y(u7y-ph/2),100,150,"U7 RELIEF POCKET  (NOTE 7)",ha="left",fs=5.8)
dim((X(oxmin),Y(oymin)),(X(51.75),Y(oymin)),Py-20,"52.70",fs=8,side=-1)
dim((X(oxmin),Y(_my[0])),(X(_mx[0]),Y(_my[0])),Py-8,f"{_mx[0]-oxmin:.2f}",fs=6.3,side=-1)
dim((X(_mx[0]),Y(_my[0])),(X(_mx[-1]),Y(_my[0])),Py-8,f"{_mx[-1]-_mx[0]:.2f} ±0.05",fs=6.3,side=-1)
dim((X(_mx[-1]),Y(_my[0])),(X(_oxmax),Y(_my[0])),Py-8,f"{_oxmax-_mx[-1]:.2f}",fs=6.3,side=-1)
dim((X(oxmin),Y(89.85)),(X(oxmin),Y(oymin)),Px-22,"90.80",vert=True,fs=8,side=1)
# 8-mount y-pattern: 4 rows -> chained pitch (each row ±0.05, per C3). Rows AND pitches are
# derived from MOUNTS; they were four typed literals until 2026-08-03.
for _a,_b in zip(_my[:-1],_my[1:]):
    dim((X(_mx[0]),Y(_b)),(X(_mx[0]),Y(_a)),Px-10,f"{_b-_a:.2f}",vert=True,fs=6.0,side=1)
dim((X(_mx[0]),Y(_my[-1])),(X(_mx[0]),Y(_my[0])),Px-17,
    f"{_my[-1]-_my[0]:.2f} ±0.05 (corners)",vert=True,fs=5.6,side=1)
ax.text(X(25.4),Y(89.85)+5,"BACK FACE (outer)   SCALE 1.5:1",ha="center",fontsize=8.5,fontweight="bold",color=INK)
# hole FCF + callout (middle column)
fcf(150,182,["POS","\u00d80.10 (M)","A","B"])
leader(X(_mx[-1]),Y(_my[-1]),150,186.3,"",ha="left")
ax.text(150,172,"8\u00d7  M2 THREAD, THRU",fontsize=7.2,fontweight="bold",color=INK)
ax.text(150,167,"\u00d81.6 TAP DRILL  \u2022  TAP FROM BACK FACE",fontsize=6.8,color=INK)
ax.text(150,162,"\u00d83.0 SPOTFACE, BACK (depth per Detail B)",fontsize=6.8,color=INK)
ax.text(150,156,"C3 = hole-pattern pitch \u00b10.05   C4 = M2 thread",fontsize=6.0,color=GRY,style="italic")
ax.text(150,148,"SECTION A-A \u2192 edge profile      DETAIL B \u2192 corner boss",fontsize=6.2,color=GRY,style="italic")

# ===================== REAR ART (machined-in; reference block) =====================
ax.text(150,140,"REAR ART \u2014 MACHINED-IN GEOMETRY  (REFERENCE; STEP GOVERNS)",fontsize=6.8,fontweight="bold",color=INK)
_ra=[
 "REEDED FIN FIELDS \u00d72 (PLAN, dashed zones):  %d RIBS/FIELD, %.2f WIDE" % (_fr.FIN_ROWS,_fr.FIN_RIB_W),
 "ON %.3f PITCH; GROOVES \u00d80.6 END-MILL ONLY (%.2f WIDE), VALLEY %.2f" % (_fr.FIN_PITCH,_fr.FIN_GROOVE,_fr.FIN_VALLEY),
 "BELOW ART FIELD (0.40 WEB); RIB TOPS +%.2f \u2014 0.05 UNDER BEARING PLANE." % _fr.FIN_PROUD,
 "",
 "MEDALLION (PLAN, circles):  \u00d8%.1f COIN SUNK %.2f BELOW ART FIELD (\u00d80.4" % (2*(_mdl.COIN_R+_mdl.RIM_W),_mdl.COIN_D),
 "END MILL), COUNTERS/REST %.2f (\u00d80.3 REST PASS); CRESTS (RING TEXT, RIM," % _mdl.REST_D,
 "HOOP, MONOGRAM, SERIAL) LEFT AT THE FRAME'S BEARING PLANE (\u22120.15),",
 "VERTICAL WALLS, NO DETACHED ISLAND UNDER %.2f. DO NOT EDGE-BREAK" % _mdl.MIN_ISLAND,
 "CREST EDGES. SERIAL (\u201cNo %s\u201d) IS PER-UNIT VARIABLE TEXT." % _mdl.SERIAL,
 "",
 "OP ORDER: ALL BACK-FACE FEATURES BEFORE CAVITY HOLLOW (SOLID-STOCK",
 "RULE). STRESS-RELIEVED STOCK \u2014 STATE CONDITION ON QUOTE.",
]
_ry=135.5
for _rl in _ra: ax.text(150,_ry,_rl,fontsize=5.6,color=INK); _ry-=3.1

# ===================== EDGE SECTION A-A =====================
S2=13.0; EX,EY=265,202
xl=lambda v:EX+v*S2; zl=lambda z:EY+(z+border)*S2
prof=[(0.10,0.0),(wall,0.0),(wall,-border+lb),(wall+lb,-border),(wall+bbw-lb,-border),(wall+bbw,-border+lb),(wall+bbw,0.0),
      (8.5,0.0),(8.5,floor),(wall+lip_w,floor),(wall+lip_w,bb-lb),(wall+lip_w-lb,bb),(wall,bb),
      (wall,wt-ease),(wall-ease,wt),(ease,wt),(0.0,wt-ease),(0.0,0.10)]
ax.add_patch(MplPoly([(xl(x),zl(z)) for x,z in prof],closed=True,fc=HATCH,ec=INK,lw=0.8,hatch="////"))
dim((xl(0.0),zl(-border)),(xl(0.0),zl(wt)),xl(0.0)-7,"3.55",vert=True,fs=7,side=1)
dim((xl(8.5),zl(0.0)),(xl(8.5),zl(floor)),xl(8.5)+7,"1.00",vert=True,fs=6.6,side=-1)
dim((xl(8.5),zl(floor)),(xl(8.5),zl(bb)),xl(8.5)+7,"1.80 ±0.05",vert=True,fs=7,side=-1)
dim((xl(0.0),zl(0.0)),(xl(wall),zl(0.0)),zl(-border)-5,"1.0",fs=6.4,side=-1)
dim((xl(wall),zl(bb)),(xl(wall+lip_w),zl(bb)),zl(bb)+7,"2.5 W-LIP (front; note 8)",fs=5.2,side=1,txtoff=1.0)
leader(xl(2.0),zl(-border+0.06),xl(4.6),zl(-border)-6.5,"2.0 BACK BORDER (UNIFORM, 4 PL)",ha="left",fs=5.0)
dim((xl(wall+lip_w+0.25),zl(-border)),(xl(wall+lip_w+0.25),zl(0.0)),xl(wall+lip_w)+3.0,"0.15",vert=True,fs=5.8,side=-1,txtoff=1.0)
leader(xl(0.05),zl(wt-0.06),xl(1.7),zl(wt)+4.5,"0.10\u00d745\u00b0 RIM (top)",ha="left",fs=5.2)
leader(xl(0.90),zl(wt-0.06),xl(4.2),zl(wt)+9.5,"0.10\u00d745\u00b0 MOUTH",ha="left",fs=5.2)
fcf(xl(3.4),zl(bb)+8,["FLAT","0.05"]); leader(xl(2.2),zl(bb),xl(3.4),zl(bb)+8+2.3,"",ha="left")
leader(xl(3.36),zl(bb-0.04),xl(5.7),zl(2.05),"0.10\u00d745\u00b0 LIP",ha="left",fs=5.2)
leader(xl(0.05),zl(0.06),xl(-2.6),zl(0.55),"0.10\u00d745\u00b0 RIM (btm)",ha="right",fs=5.0)
leader(xl(1.08),zl(-0.10),xl(1.35),zl(-border)-9,"0.10\u00d745\u00b0 FRAME (2 PL)",ha="left",fs=5.0)
leader(xl(3.42),zl(-0.10),xl(1.35),zl(-border)-9,"",ha="left")
ax.text(xl(0.06),zl(floor)+0.8,
        ("  floor %.2f TRUE (%.2f local under the U7 pocket, note 7)   •   PCB recess 0.60 (0.60 mm board)"
         % (floor, floor-U7_POCKET)) if U7_POCKET > 0 else
        ("  floor %.2f TRUE, UNIFORM (no local relief)   •   PCB recess 0.60 (0.60 mm board)" % floor),
        fontsize=5.7,color=GRY,va="bottom")
ax.text(EX+2,EY-11,"SECTION A-A  (edge)   SCALE 13:1",fontsize=8.5,fontweight="bold",color=INK)
ax.text(EX+2,EY-16.5,"C1 = cavity depth    C2 = PCB-rest-plane flatness    (back face down; PCB drops in from top)",fontsize=6,color=GRY,style="italic")

# ===================== DETAIL B (corner boss, section) =====================
S3=13.0; BX,BY=312,112
bx=lambda v:BX+v*S3; bz=lambda z:BY+(z+border)*S3
ax.add_patch(MplPoly([(bx(-4),bz(0)),(bx(4),bz(0)),(bx(4),bz(floor)),(bx(-4),bz(floor))],closed=True,fc=HATCH,ec=INK,lw=0.6,hatch="////"))
for s in (1,-1):
    ax.add_patch(MplPoly([(bx(x),bz(z)) for x,z in [(s*0.8,0.20),(s*1.5,0.20),(s*1.5,bb),(s*0.8,bb)]],closed=True,fc=HATCH,ec=INK,lw=0.7,hatch="////"))
    ax.add_patch(MplPoly([(bx(x),bz(z)) for x,z in [(s*1.5,-border+lb),(s*(1.5+lb),-border),(s*(2.6-lb),-border),(s*2.6,-border+lb),(s*2.6,bb),(s*1.5,bb)]],closed=True,fc=HATCH,ec=INK,lw=0.7,hatch="////"))
ax.add_patch(Rectangle((bx(-4),bz(bb)),8*S3,board*S3,fill=False,ec=GRY,lw=0.6,ls=(0,(5,3))))
ax.add_patch(Rectangle((bx(-1.0),bz(wt)),2.0*S3,1.6*S3,fill=False,ec=GRY,lw=0.6,ls=(0,(5,3))))
ax.add_patch(Rectangle((bx(-0.9),bz(0.20)),1.8*S3,(wt-0.20)*S3,fill=False,ec=GRY,lw=0.6,ls=(0,(5,3))))
ax.plot([bx(0),bx(0)],[bz(-border)-3,bz(wt)+1.6*S3+3],lw=0.4,color=INK,ls=(0,(8,3,1,3)))
dim((bx(-2.6),bz(-border)),(bx(2.6),bz(-border)),bz(-border)-12,"\u00d85.20",fs=6.8,side=-1)
dim((bx(-1.5),bz(-border)),(bx(1.5),bz(-border)),bz(-border)-5,"\u00d83.0 SPOTFACE (BACK)",fs=6.3,side=-1)
dim((bx(2.6),bz(-border)),(bx(2.6),bz(0.0)),bx(2.6)+3,"0.15",vert=True,fs=5.8,side=-1,txtoff=1.0)
leader(bx(0.0),bz(1.5),bx(4.6),bz(1.9),"M2 THREAD\n\u00d81.6 TAP DRILL, THRU\nTAP FROM BACK",ha="left",fs=6.2)
leader(bx(1.0),bz(0.20),bx(3.0),bz(0.20)-7,"spotface bottom = M2\u00d73\nscrew-tip plane (flush)",ha="left",fs=5.7)
ax.text(bx(0),bz(wt)+1.6*S3+4,"PCB + M2\u00d73 BRASS SCREW \u2014 REF, NOT THIS PART",ha="center",fontsize=5.7,color=GRY,style="italic")
leader(bx(2.6),bz(-0.07),bx(4.4),bz(-border)-2,"0.10\u00d745\u00b0 BOSS/SPOTFACE (typ)",ha="left",fs=5.0)
ax.text(BX-92,BY-25,"DETAIL B   (corner boss)   13:1",fontsize=8.5,fontweight="bold",color=INK)

# ===================== CRITICAL DIMS + NOTES =====================
ax.text(20,78,"CRITICAL DIMENSIONS  \u2014  C1 & C3 TOLERANCED \u00b10.05 (MARKED ON VIEWS); ALL OTHER FEATURES PER ISO 2768-1 (MEDIUM)",fontsize=7.4,fontweight="bold",color=INK)
ct=[["C1","Cavity depth  (boss-top plane \u2192 cavity floor)","1.80  ±0.05"],
    ["C2","PCB-rest plane flatness  (lip + 8 bosses)","FLAT  0.05"],
    ["C3",f"8\u00d7 mounting holes  (x {_mx[-1]-_mx[0]:.2f}; y rows "
          f"{'/'.join(f'{v:g}' for v in _my)})","\u00b10.05  (linear)"],
    ["C4","Mounting holes \u2014 tapped, thru, from back","M2   /   \u00d81.6 drill"]]
yy=72.5
for r in ct:
    ax.text(20,yy,r[0],fontsize=6.7,fontweight="bold",color=INK)
    ax.text(28,yy,r[1],fontsize=6.5,color=INK); ax.text(120,yy,r[2],fontsize=6.5,color=INK); yy-=4.2
ax.text(20,52.5,"NOTES",fontsize=7.4,fontweight="bold",color=INK)
notes=[
 "1. MATERIAL: TITANIUM Gr5 (TC4) = Ti-6Al-4V GRADE 5.",
 "2. FINISH: BEAD-BLAST MATTE, ALL OVER. NO MARKING SERVICE — THE REAR ART (REEDED FIELDS + MEDALLION) IS MACHINED-IN, IN THE STEP (SEE REAR ART BLOCK). BEARING PLANE (FRAME + MEDALLION CRESTS) HAND-LAPPED BY CUSTOMER AFTER BLAST — NO SHOP ACTION.",
 "3. GENERAL TOLERANCE PER ISO 2768-1 (MEDIUM). C1-C4 TOLERANCED AS LISTED; C1 & C3 = ±0.05. DATUMS: A = LEFT EDGE, B = BOTTOM EDGE, C = PCB-REST PLANE.",
 "4. BRACE REGISTRATION: THE RESIN H-BRACE REGISTERS TO THIS SHELL BY FITMENT - ITS 4 OUTBOARD RAILS + THE COMPONENT POCKETS + THE BOARD PRESS-FIT. NO LOCATOR PILLARS; THE CAVITY FLOOR IS A FULL 1.00 EVERYWHERE.",
 "5. EDGE BREAKS - ALL 0.10x45°, FELT NOT SEEN, MODELED.  CALLED OUT ON SEC A-A / DETAIL B:  RIM = outer rim (top & bottom);  MOUTH = recess mouth (around PCB);  LIP = inner (cavity-side) lip edge;  FRAME = proud back-frame bottom edges;  BOSS = boss + spotface bottom edges (Detail B).  BREAK ALL OTHER EXPOSED EDGES 0.10x45°.  CONCAVE JUNCTION CORNERS (BOSS-TO-WALL + EAST-LIP STEPS) LEFT SHARP IN THE MODEL: FINISH WITH A Ø2.0 mm TOOL = R1.0 AS-MILLED. THE RESIN BRACE IS RELIEVED TO CLEAR R1.0 AT THESE CORNERS.",
 ("6. FLOOR IS A TRUE %.2f (%.2f LOCAL UNDER THE U7 POCKET), AT THE ~1.0 Ti MIN-WALL GUIDANCE SO IT ALSO CLEARS ALUMINIUM / COPPER / STAINLESS." % (floor, floor-U7_POCKET))
   if U7_POCKET > 0 else
   ("6. FLOOR IS A TRUE %.2f, UNIFORM ACROSS THE CAVITY, AT THE ~1.0 Ti MIN-WALL GUIDANCE SO IT ALSO CLEARS ALUMINIUM / COPPER / STAINLESS." % floor),
 "    CAVITY 1.80 +-0.05 -> 1.75 WORST-CASE, MINUS WS17 1.70 MAX (DATASHEET CASE WS17 HEIGHT) = 0.05 NON-CONTACT; THE BRACE + SOLAR-CELL SANDWICHES CARRY THE BOARD.",
 ("7. U7 RELIEF POCKET: 7.8 x 5.4 CENTERED (28.1, 37.3) ON THE CAVITY FLOOR, %.2f DEEP (LOCAL FLOOR %.2f) - U7 (%.2f) KEEPS 0.10 AIR. GENERAL FLOOR %.2f. MODELED IN THE STEP."
   % (U7_POCKET, floor-U7_POCKET, U7_H, floor))
   if U7_POCKET > 0 else
   ("7. NO U7 RELIEF POCKET. U7 IS THE %.2f mm MB85RC512TY DFN-8, WELL UNDER THE %.2f CAP-LIMITED CAVITY, SO THE FLOOR IS UNIFORM %.2f. (A POCKET EXISTED FOR A 1.75 SOIC-8 THE v4 BOARD DOES NOT CARRY.)"
   % (U7_H, _CAPH, floor)),
 "8. FRONT SUPPORT LIP IS ASYMMETRIC (SECTION A-A): WEST 2.5 / NORTH 2.0 / SOUTH 2.0 FOR PCB RIGIDITY; EAST 1.0 CLEARING THE JP1/TP1 PADS, THE NFC COIL (A GROUNDED LIP WOULD DETUNE IT), AND C7 (x49.55, THE ONE EAST-EDGE PART LEFT AFTER v4 REMOVED THE Q1/U4/R7/R9 CLAMP CLUSTER + D9/D10/D11); WIDENING TO 2.5 ONLY AT THE SOUTH END (y0-10, CLEAR OF ALL). THE EXTERIOR BACK BORDER (PLAN) IS INDEPENDENT AND UNIFORM 2.0 ON ALL 4 SIDES.",
 "9. NO INTERNAL RIBS OR SUPPORT POSTS: THE RESIN BRACE (SEPARATE PART) CARRIES CENTER SUPPORT. A PCB LAYOUT CHANGE = A BRACE REPRINT, NOT A SHELL RE-MACHINE.",
 "10. PCB RECESS = 0.60 DEEP (RECEIVES THE 0.60 mm BOARD; SLIP FIT, NOT A PRESS FIT). 3D STEP GOVERNS ALL GEOMETRY; STL NOT FOR CNC.",
 "11. PART = BACK-SHELL ONLY. PCB, RESIN BRACE, AND 8× M2×3 BRASS SLOTTED-CHEESE SCREWS (HEAD Ø3.8) SUPPLIED SEPARATELY.",
]
yy=48.0
for n in notes: ax.text(20,yy,n,fontsize=5.85,color=INK); yy-=3.32

# ===================== TITLE BLOCK =====================
tb_x,tb_y,tb_w,tb_h=288,12,120,46
ax.add_patch(Rectangle((tb_x,tb_y),tb_w,tb_h,fill=False,ec=INK,lw=0.9))
for yl in (tb_y+34,tb_y+24,tb_y+15,tb_y+8): ax.plot([tb_x,tb_x+tb_w],[yl,yl],lw=0.4,color=INK)
ax.plot([tb_x+60,tb_x+60],[tb_y,tb_y+15],lw=0.4,color=INK)
ax.text(tb_x+tb_w/2,tb_y+40,"SOLAR-GLOW DRH v3.0  —  Ti BACK-SHELL (0.6mm-BOARD DUMB BOX)",ha="center",va="center",fontsize=7.5,fontweight="bold",color=INK)
ax.text(tb_x+3,tb_y+29,"DWG  solar-glow-drh-v3_0-backshell-0p6b-brace",fontsize=5.9,va="center",color=INK)
ax.text(tb_x+tb_w-3,tb_y+29,"REV  v3.0",ha="right",fontsize=6.6,va="center",color=INK)
ax.text(tb_x+3,tb_y+19.5,"MATERIAL  Ti Gr5 (TC4)",fontsize=6.6,va="center",color=INK)
ax.text(tb_x+tb_w-3,tb_y+19.5,"FINISH  BEAD-BLAST + LAP (CUSTOMER)",ha="right",fontsize=6.6,va="center",color=INK)
ax.text(tb_x+3,tb_y+11.2,"UNITS  mm",fontsize=6.4,va="center",color=INK)
ax.text(tb_x+63,tb_y+11.2,"SCALE  AS NOTED",fontsize=6.4,va="center",color=INK)
ax.text(tb_x+3,tb_y+4,"BBOX 52.70 x 90.80 x 3.55   3rd-angle",fontsize=6.0,va="center",color=INK)
ax.text(tb_x+tb_w-3,tb_y+4,"SHEET 1/1",ha="right",fontsize=6.4,va="center",color=INK)

# ===================== TOLERANCE BLOCK (above title block) =====================
tx,ty,tw,th=288,61,120,33
ax.add_patch(Rectangle((tx,ty),tw,th,fill=False,ec=INK,lw=0.9))
ax.plot([tx,tx+tw],[ty+th-6.5,ty+th-6.5],lw=0.4,color=INK)
ax.text(tx+tw/2,ty+th-3.3,"GENERAL TOLERANCES  (UNLESS OTHERWISE NOTED, mm)",ha="center",va="center",fontsize=6.2,fontweight="bold",color=INK)
tol=[("LINEAR & HOLE-POSITION DIMS","ISO 2768-m"),
     ("CAVITY DEPTH  C1  (SECTION A-A)","1.80 \u00b10.05"),
     ("HOLE-PATTERN PITCH  C3  (8 HOLES)",
      f"x {_mx[-1]-_mx[0]:.2f} / y "
      f"{'-'.join(f'{b-a:g}' for a,b in zip(_my[:-1],_my[1:]))}  \u00b10.05"),
     ("PCB-REST FLATNESS  C2","FLAT 0.05")]
yt=ty+th-11.5
for lab,val in tol:
    ax.text(tx+3,yt,lab,fontsize=5.85,va="center",color=INK)
    ax.text(tx+tw-3,yt,val,ha="right",fontsize=5.85,va="center",fontweight="bold",color=INK)
    yt-=5.3

# Write next to this script by default (override with $OUT_DIR). This used to be a hardcoded
# /mnt/user-data/outputs/, which exists only on the machine this was first authored on, so a
# plain checkout could not regenerate the sheet -- same fix as the backshell generator.
import os as _o
_OUT = _o.environ.get("OUT_DIR") or _o.path.dirname(_o.path.abspath(__file__))
_o.makedirs(_OUT, exist_ok=True)
# CreationDate=None: matplotlib stamps a write time into the PDF, so an unchanged drawing
# rewrote itself on every run. That is not cosmetic once CI regenerates these -- a job that
# commits its outputs would produce a "changed drawing" commit for every board edit that did
# not touch the drawing at all, and a real change would be invisible among them. PNG carries
# no such stamp and is already reproducible.
fig.savefig(_o.path.join(_OUT,"solar-glow-drh-v3_0-backshell-0p6b-brace-DRAWING.pdf"),facecolor="white",
            metadata={"CreationDate": None})
fig.savefig(_o.path.join(_OUT,"solar-glow-drh-v3_0-backshell-0p6b-brace-DRAWING.png"),dpi=150,facecolor="white")
print("saved")
