#!/usr/bin/env python3
"""Overlay the two solar-cell (PV1/PV2) borders onto the KiBot board renders.

Auto-calibrates board-mm -> pixels from each render's own board outline (the
non-black extent), so it stays correct if Generated/docs/*.png is regenerated by
CI. The B.Cu (bottom) render is a left-right mirror of the front, handled here;
because both cells are centred on x = 25.4 mm their borders land at the same
pixels either way -- the point of the back overlay is to show which B-side parts
sit under each cell.

Geometry from the committed sources:
  PV1 c(25.4, 17.0), PV2 c(25.4, 71.9), SM141K06TF body 42 x 23 mm, F.Cu
  mounts (3,3)(47.8,3)(3,85.9)(47.8,85.9); M2 head Ø3.8 (DIN 84, enclosure cad.py)

Run from the repo root:  python3 scripts/gen_panel_overlay.py
Writes beside the CWD (or $OUT_DIR) -- ON-DEMAND analysis output, not repo content. It used
to write into docs/, but its two PNGs were culled as unreferenced on 2026-07-31 and writing
there again would just recreate files nothing displays; check [9] guards displayed images
only, so they would rot silently a second time.
"""
import os
from PIL import Image, ImageDraw, ImageFont

BW, BH = 50.80, 88.90                      # board outline (Edge.Cuts)
PANELS = {"PV1": (25.4, 17.0), "PV2": (25.4, 71.9)}
PW, PL = 42.0, 23.0                        # SM141K06TF body
MOUNTS = [(3.0, 3.0), (47.8, 3.0), (3.0, 85.9), (47.8, 85.9)]
HEAD_R = 1.9                               # Ø3.8 M2 head radius
FONT_B = "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf"

def _board_edges(px, W, H):
    """Return (x_left, x_right, y_top, y_bottom) px of the board outline."""
    lum = lambda p: 0.3 * p[0] + 0.59 * p[1] + 0.11 * p[2]
    def scan(fixed, order, axis):
        for i in order:
            x, y = (i, fixed) if axis == "x" else (fixed, i)
            if lum(px[x, y]) > 20:
                return i
        return 0
    cx, cy = W // 2, H // 2
    return (scan(cy, range(W), "x"), scan(cy, range(W - 1, -1, -1), "x"),
            scan(cx, range(H), "y"), scan(cx, range(H - 1, -1, -1), "y"))

def make(render_path, out_path, mirrored, side_label):
    im = Image.open(render_path).convert("RGB")
    W, H = im.size
    xl, xr, yt, yb = _board_edges(im.load(), W, H)
    sx, sy = (xr - xl) / BW, (yb - yt) / BH
    X = (lambda mm: xl + sx * (BW - mm)) if mirrored else (lambda mm: xl + sx * mm)
    Y = lambda mm: yt + sy * mm

    SC = 2                                  # supersample for crisp overlay
    big = im.resize((W * SC, H * SC), Image.LANCZOS).convert("RGBA")
    ov = Image.new("RGBA", big.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(ov)
    BX, BY = lambda mm: X(mm) * SC, lambda mm: Y(mm) * SC
    fF = ImageFont.truetype(FONT_B, 34)
    fS = ImageFont.truetype(FONT_B, 26)
    CY, CYf, RED = (60, 224, 224, 255), (60, 224, 224, 38), (255, 110, 90, 230)

    for name, (pcx, pcy) in PANELS.items():
        xs = [BX(pcx - PW / 2), BX(pcx + PW / 2)]
        ys = [BY(pcy - PL / 2), BY(pcy + PL / 2)]
        x0, x1, y0, y1 = min(xs), max(xs), min(ys), max(ys)
        d.rectangle([x0, y0, x1, y1], outline=CY, width=4, fill=CYf)
        for qx in (x0, x1):
            for qy in (y0, y1):
                d.ellipse([qx - 7, qy - 7, qx + 7, qy + 7], fill=CY)
        tx, ty = x0 + 10, y0 + 8
        d.rounded_rectangle([tx - 4, ty - 2, tx + 96, ty + 40], radius=6, fill=(10, 20, 30, 205))
        d.text((tx, ty), name, font=fF, fill=CY)

    for mx, my in MOUNTS:                    # Ø3.8 M2 head footprints
        r = HEAD_R * sx * SC
        d.ellipse([BX(mx) - r, BY(my) - r, BX(mx) + r, BY(my) + r], outline=RED, width=3)

    # side watermark, auto-sized, bottom-centre (clear of the corner mounts)
    lbl_w = d.textlength(side_label, font=fS)
    pad = 13
    cx0 = (big.size[0] - lbl_w) / 2 - pad
    d.rounded_rectangle([cx0, big.size[1] - 52, cx0 + lbl_w + 2 * pad, big.size[1] - 12],
                        radius=7, fill=(10, 20, 30, 210))
    d.text((cx0 + pad, big.size[1] - 48), side_label, font=fS, fill=(150, 210, 225, 255))

    Image.alpha_composite(big, ov).convert("RGB").save(out_path)
    print(f"wrote {os.path.relpath(out_path)}  | scale {sx:.3f}/{sy:.3f} px/mm  mirrored={mirrored}")

if __name__ == "__main__":
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    g = lambda p: os.path.join(root, p)
    out = os.environ.get("OUT_DIR") or os.getcwd()
    make(g("Generated/docs/solar-glow-drh-v4_0-top.png"),
         os.path.join(out, "solar-glow-drh-panel-outline-top.png"), False, "F.Cu (front)")
    make(g("Generated/docs/solar-glow-drh-v4_0-bottom.png"),
         os.path.join(out, "solar-glow-drh-panel-outline-bottom.png"), True, "B.Cu (back, mirrored)")
